SOURCES = style_node_parser.cc \
			style_node.cc

MAIN_SOURCE = main.cc
LIBRARY_OUT = style.o
INTERGRATE_TEST_OUT = styleprog.out

LIBRARY_EXTRAS = ../html/html.o \
				../css/css.o

all: $(LIBRARY_OUT)
include ../Makefile.common