SOURCES = layout_node.cc

MAIN_SOURCE = main.cc
LIBRARY_OUT = layout.o
INTERGRATE_TEST_OUT = layoutprog.out

LIBRARY_EXTRAS = ../style/style.o \
				../html/html.o \
				../css/css.o

all: $(LIBRARY_OUT)
include ../Makefile.common